name: terraform

on:
  push:
    paths:
      - "infra/terraform/**"
      - ".github/workflows/ci-terraform.yml"
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/live/dev/s3
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      - name: Terraform init
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -input=false -lock=false -out=tfplan
      - name: Terraform show
        run: terraform show -json tfplan > plan.json
      - name: Install OPA and Conftest
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa && sudo mv opa /usr/local/bin/opa
          curl -L https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz | tar zx -C /usr/local/bin
      - name: OPA unit tests
        run: opa test ../../../../../security/opa
      - name: Conftest policy check
        run: conftest test plan.json --policy ../../../../../security/opa
      - name: Upload plan.json
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: infra/terraform/live/dev/s3/plan.json
