name: terraform

on:
  push:
    paths:
      - "infra/terraform/**"
      - ".github/workflows/ci-terraform.yml"
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/live/dev/s3
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      - name: Terraform init
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -input=false -lock=false
